// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://byuphfwqugmgewmvvjzz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ5dXBoZndxdWdtZ2V3bXZ2anp6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIwMDY5NjYsImV4cCI6MjA2NzU4Mjk2Nn0.KB2YoaI8prBbDXqg-H1zCtA7JsRL2lFQFygPvFOGt88";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});